name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test (ruby ${{ matrix.ruby }} / rails ${{ matrix.rails_version }} / blacklight ${{ matrix.blacklight_version }} ${{ matrix.additional_name }})
    strategy:
      matrix:
        ruby: ['3.3']
        rails_version: ['7.1.4', '7.2.1']
        blacklight_version: ['~> 7.0']
        additional_name: ['']
        include:
        - ruby: '3.3'
          rails_version: '7.2.1'
          blacklight_version: '~> 8.0'
          additional_name: ''
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      BLACKLIGHT_VERSION: ${{ matrix.blacklight_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies with Rails ${{ matrix.rails_version }}
      run: bundle install
    - name: Run tests
      run: bundle exec rake
